#!/bin/sh

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

SRV_ID=org.webosinternals.pulsecontrol.srv
SRV_DIR=/media/cryptofs/apps/usr/palm/services/${SRV_ID}

rm -f /var/cache/configurator/_media_cryptofs_apps_usr_palm_services_${SRV_ID}_configuration_db_permissions_${SRV_ID}

#/usr/bin/pkill switcher.srv.js || true

/usr/bin/ls-control scan-services || true
